name: Release

on:
    # This job runs when a new release is published
    release:
        types: [published]

permissions:
    id-token: write # Required for OIDC
    contents: read

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
              with:
                  ref: ${{ github.event.release.tag_name }}
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org
            # Ensure npm 11.5.1 or later for trusted publishing
            - run: npm install -g npm@latest
            - uses: actions/cache@v6.1.0
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
            - run: echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
            - run: test -n "$RELEASE_VERSION"
            - run: npm i
            - run: npm version $RELEASE_VERSION --no-git-tag-version
            - run: npm publish --access public
